import os
import json

with open("strings_extracted.json", "r") as f:
    data = json.load(f)

strings_map = data["strings"]
file_replacements = data["files"]

# Group by category
categories_map = {}
for string_val, info in strings_map.items():
    cat = info["category"]
    if cat not in categories_map:
        categories_map[cat] = []
    categories_map[cat].append(info)

# 1. Generate L10n.swift
l10n_content = """import SwiftUI
import Foundation

/// Scalable Localization System wrapper
public enum L10n {
"""

for cat, items in categories_map.items():
    l10n_content += f"    public enum {cat} {{\n"
    for item in items:
        key = item["key"]
        l10n_key = f"{cat.lower()}.{key}"
        l10n_content += f'        public static let {key}: LocalizedStringKey = "{l10n_key}"\n'
    l10n_content += "    }\n\n"

l10n_content += "}\n"

with open("/Users/aplle/Desktop/swift learning/FinaLit/FinaLit/Core/Localization/L10n.swift", "w") as f:
    f.write(l10n_content)

# 2. Generate Localizable.strings
strings_content = """/* 
  Localizable.strings
  FinaLit
  Auto-generated by FinaLit Localization Wizard
*/\n\n"""

# Group visually by category in the strings file too
for cat, items in categories_map.items():
    strings_content += f"/* --- {cat} --- */\n"
    for item in items:
        key = item["key"]
        l10n_key = f"{cat.lower()}.{key}"
        
        orig = item["original"]
        # Escape quotes just in case
        orig = orig.replace('"', '\\"')
        
        strings_content += f'"{l10n_key}" = "{orig}";\n'
    strings_content += "\n"

# Ensure dir exists
os.makedirs("/Users/aplle/Desktop/swift learning/FinaLit/FinaLit/App/en.lproj", exist_ok=True)
with open("/Users/aplle/Desktop/swift learning/FinaLit/FinaLit/App/en.lproj/Localizable.strings", "w") as f:
    f.write(strings_content)

# 3. Replace in Swift files
modified_count = 0
for filepath, replacements in file_replacements.items():
    with open(filepath, "r") as f:
        content = f.read()
        
    for rep in replacements:
        original_match = rep["original_match"]
        replacement_text = rep["replacement"]
        content = content.replace(original_match, replacement_text)
        
    with open(filepath, "w") as f:
        f.write(content)
    modified_count += 1

print(f"Successfully generated L10n.swift and Localizable.strings.")
print(f"Modified {modified_count} Swift files.")
